import type { Metadata } from 'next'
import { Poppins, Roboto_Slab } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ 
  weight: ["100", "300","400", "500", "700", "900"], 
  subsets: ["latin"],  
  display: 'swap',
  variable: '--font-poppins'
}
  )
const robotoslab = Roboto_Slab({ 
  weight: ["100", "300","400", "500", "700", "900"], 
  subsets: ["latin"],  
  display: "swap",
  variable: '--font-robotoslab'
})

export const metadata: Metadata = {
  title: 'GS-Biscards',
  description: 'Generated by create next app, typescript, tailwind',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${robotoslab.variable} ${poppins.variable}`}>
        {children}
        </body>
    </html>
  )
}
