import type { Metadata } from 'next'
import { Arvo, Lato, Poppins, Roboto, Roboto_Slab } from 'next/font/google'
import './globals.css';

const arvo = Arvo({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-arvo'
});
const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-lato'
});
const poppins = Poppins({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-poppins'
});
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: '--font-roboto'
});
const robotoslab = Roboto_Slab({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: '--font-robotoslab'
});

export const metadata: Metadata = {
  title: 'GuilSoft',
  description: 'Generated by create next app, typescript, tailwind css',
  icons: { icon: 'asset/icons/guilsoft.png' },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${arvo.variable} ${lato.variable} ${poppins.variable} ${roboto.variable}  ${robotoslab.variable} `}>
        {children}
      </body>
    </html>
  )
}